# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:

  vendor-portal:
    image: ravilohana/selenium-docker
    environment:
      - BROWSER
      - HUB_HOST=selenium-hub
      - THREAD_COUNT=4
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output


  flight-reservation:
      image: ravilohana/selenium-docker
      environment:
        - BROWSER
        - HUB_HOST=selenium-hub
        - THREAD_COUNT=4
        - TEST_SUITE=flight-reservation.xml
      volumes:
        - ./output/flight-reservation:/home/selenium-docker/test-output


